themeapp/urls.py
from django.urls import path
from .views import *

app_name = "themeapp"
urlpatterns = [
    path("", HomeView.as_view(), name='home'),
    path("gallery/", GalleryView.as_view(), name='gallery'),
    path("about/", AboutView.as_view(), name='about'),
    path("contact/", ContactView.as_view(), name='contact'),
    path("firm-admin/", AdminHomeView.as_view(), name='adminhome'),

    # food urls
    path("firm-admin/food/list/", AdminFoodListView.as_view(), name='adminfoodlist'),
    path("firm-admin/food/add/", AdminFoodCreateView.as_view(),
         name='adminfoodcreate'),
    path("firm-admin/food/<int:pk>/update/",
         AdminFoodUpdateView.as_view(), name='adminfoodupdate'),
    path("firm-admin/food/<int:pk>/delete/",
         AdminFoodDeleteView.as_view(), name='adminfooddelete'),

    # Category urls
    path("firm-admin/category/create/",
         AdminCategoryCreateView.as_view(), name='admincategorycreate'),
    path('firm-admin/category/list/',
         AdminCategoryListView.as_view(), name="admincategorylist"),
    path("firm-admin/category/<int:pk>/update/",
         AdminFoodUpdateView.as_view(), name='admincategoryupdate'),
    path("firm-admin/category/<int:pk>/delete/",
         AdminFoodDeleteView.as_view(), name='admincategorydelete'),

    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),


]

themeproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('themeapp.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

themeapp/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to="category", null=True, blank=True)

    def __str__(self):
        return self.title


class Food(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to="Food")
    description = models.TextField()
    price = models.DecimalField(max_digits=19, decimal_places=2)

    def __str__(self):

        return self.name

# class slider


class Slider(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='slider')

    def __str__(self):
        return self.title

# class testimonial


class Testimonial(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='testimonial')
    organization = models.CharField(max_length=200)
    review = models.TextField()

    def __str__(self):
        return self.name


# class gallery
class Gallery(models.Model):
    image = models.ImageField(upload_to='gallery')
    caption = models.CharField(max_length=200)

    def __str__(self):
        return self.caption

themeapp/forms.py
from django import forms
from .models import *


class FoodForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = ['name', 'category', 'image', 'description', 'price']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter food name....'
            }),
            'category': forms.Select(attrs={
                'class': 'form-control'
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control'
            }),

            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Enter description....'

            }),
            'price': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter price of the food....'

            })
        }


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

themeapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import *
from .models import*
from .forms import*
from django.contrib.auth import authenticate, login, logout


class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(seelf, **kwargs):
        context = super().get_context_data(**kwargs)
        context["myfoods"] = Food.objects.all()
        context["mytestimonials"] = Testimonial.objects.all()
        context["mygallerys"] = Gallery.objects.all()
        context["mysliders"] = Slider.objects.all()
        context["mycategorys"] = Category.objects.all()

        return context


class AboutView(TemplateView):
    template_name = "about.html"


class ContactView(TemplateView):
    template_name = "contact.html"


class GalleryView(TemplateView):
    template_name = "gallery.html"

    def get_context_data(seelf, **kwargs):
        context = super().get_context_data(**kwargs)
        context["mygallerys"] = Gallery.objects.all()

        return context


class AdminRequiredMixin(object):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            pass
        else:
            return redirect("/login/")

        return super().dispatch(request, *args, **kwargs)


class AdminHomeView(AdminRequiredMixin, TemplateView):
    template_name = "admintemplates/adminhome.html"


class AdminFoodListView(AdminRequiredMixin, ListView):
    template_name = "admintemplates/adminfoodlist.html"
    queryset = Food.objects.all()
    context_object_name = 'foodlist'


class AdminFoodCreateView(AdminRequiredMixin, CreateView):
    template_name = "admintemplates/adminfoodcreate.html"
    form_class = FoodForm
    success_url = '/firm-admin/food/list/'


class AdminFoodUpdateView(AdminRequiredMixin, UpdateView):
    template_name = "admintemplates/adminfoodcreate.html"
    form_class = FoodForm
    model = Food
    success_url = '/firm-admin/food/list/'


class AdminFoodDeleteView(AdminRequiredMixin, DeleteView):
    template_name = "admintemplates/adminfooddelete.html"
    model = Food
    success_url = '/firm-admin/food/list/'


class AdminCategoryCreateView(AdminRequiredMixin, CreateView):
    template_name = "admintemplates/adminfoodcategory.html"
    form_class = CategoryForm
    success_url = '/firm-admin/food/categorylist/'


class AdminCategoryListView(AdminRequiredMixin, ListView):
    template_name = "admintemplates/admincategorylist.html"
    queryset = Category.objects.all()
    context_object_name = "allcategory"


class AdminFoodUpdateView(AdminRequiredMixin, UpdateView):
    template_name = "admintemplates/adminfoodcategory.html"
    model = Category
    form_class = CategoryForm
    success_url = '/firm-admin/category/list/'


class AdminFoodDeleteView(AdminRequiredMixin, DeleteView):
    template_name = "admintemplates/adminfoodcategorydelete.html"
    model = Category
    success_url = '/firm-admin/category/list/'


class LoginView(FormView):
    template_name = "login.html"
    form_class = LoginForm
    success_url = "/firm-admin"

    def form_valid(self, form):
        a = form.cleaned_data["username"]
        b = form.cleaned_data.get("password")
        user = authenticate(username=a, password=b)
        if user is not None:
            login(self.request, user)
        else:
            return render(self.request, self.template_name,
                          {"error": "Invalid Credentials", 'form': form})

        return super().form_valid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)

        return redirect("/")

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block abc %}main-banner-2{% endblock %}
{% block aboutpage %}active{% endblock %}




{% block body %}
	<!-- page details -->
	<div class="breadcrumb-w3ls py-1">
		<div class="container">
			<ol class="breadcrumb m-0">
				<li class="breadcrumb-item">
					<a href="index.html">Home</a>
				</li>
				<li class="breadcrumb-item active" aria-current="page">About Us</li>
			</ol>
		</div>
	</div>
	<!-- //page details -->

	<!-- about  -->
	<section class="about-inner py-5">
		<div class="container pt-xl-5 pt-lg-3">
			<h3 class="title-w3 mb-5 font-weight-bold">About Us <span>Something about us</span></h3>
			<div class="row">
				<div class="col-lg-6 w3lsits_works-grid mt-xl-4">
					<div class="wthree-bottom">
						<h6 class="subheading-w3ls text-uppercase text-dark mb-4">DEAL OF THE <span class="font-weight-bold">DAY</span>
							organic good <span class="font-weight-bold">foods 50%</span> off</h6>
						<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, eaque ipsa
							quae ab illo inventore veritatis et quasi architecto.</p>
						<a href="about.html" class="btn button-style mt-sm-5 mt-4">Read More</a>
					</div>
				</div>
				<div class="col-lg-6 w3lsits_works-grid1 mt-lg-0 mt-sm-5 mt-4">
					<img src="{% static 'images/about.jpg' %}" alt="" class="img-fluid" />
				</div>
			</div>
		</div>
	</section>
	<!-- //about -->

	<!-- middle -->
	<section class="what-w3ls">
		<div class="container-fluid py-xl-5 py-lg-3">
			<div class="offset-xl-7 offset-lg-6 offset-md-4 offset-sm-2">
				<div class="grids-whtas pr-xl-5">
					<h3 class="tittle text-wh mb-5 font-weight-bold">763+ fruits, vegetables & lot more</h3>
					<p class="lead text-li">Fresh From Our Farm ut leo cursus rhoncus. Nullam dui mi, vulputate ac metus at,
						semper varius orci. Nulla accumsan ac elit in congue.</p>
					<hr class="my-4">
					<p class="text-li">Rerum hic tenetur a sapiente delectus reiciendis maiores alias consequatur aut consequat
						sapien ut leo cursus
						rhoncus.Nullam dui mi, vulputate ac metus.</p>
					<a href="about.html" class="btn button-style mt-sm-5 mt-4">Read More</a>
				</div>
			</div>
		</div>
	</section>
	<!-- //middle -->

	<!-- team -->
	<section class="team pb-5" id="farmer">
		<div class="container pb-xl-5 pb-lg-3">
			<h3 class="title-w3 mb-5 font-weight-bold">Our Farmers <span>Caption Here</span></h3>
			<div class="row inner-sec-w3layouts-w3pvt-lauinfo">
				<div class="col-md-4 team-grids text-center">
					<img src="{% static 'images/team1.jpg' %}" class="img-fluid" alt="">
					<div class="team-info">
						<div class="caption mb-3">
							<h4>John Doe</h4>
						</div>
						<div class="social-icons-section">
							<a class="fac" href="#">
								<i class="fa fa-facebook"></i>
							</a>
							<a class="twitter mx-2" href="#">
								<i class="fa fa-twitter"></i>
							</a>
							<a class="google" href="#">
								<i class="fa fa-google-plus"></i>
							</a>
						</div>
					</div>
				</div>
				<div class="col-md-4 team-grids my-md-0 my-4 text-center">
					<img src="{% static 'images/team3.jpg' %}" class="img-fluid" alt="">
					<div class="team-info">
						<div class="caption mb-3">
							<h4>Adam Ster</h4>
						</div>
						<div class="social-icons-section">
							<a class="fac" href="#">
								<i class="fa fa-facebook"></i>
							</a>
							<a class="twitter mx-2" href="#">
								<i class="fa fa-twitter"></i>
							</a>
							<a class="google" href="#">
								<i class="fa fa-google-plus"></i>
							</a>
						</div>
					</div>
				</div>
				<div class="col-md-4 team-grids text-center">
					<img src="{% static 'images/team2.jpg' %}" class="img-fluid" alt="">
					<div class="team-info">
						<div class="caption mb-3">
							<h4>Chris Tina</h4>
						</div>
						<div class="social-icons-section">
							<a class="fac" href="#">
								<i class="fa fa-facebook"></i>
							</a>
							<a class="twitter mx-2" href="#">
								<i class="fa fa-twitter"></i>
							</a>
							<a class="google" href="#">
								<i class="fa fa-google-plus"></i>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- team -->

	<!-- testimonials -->
	<div class="testimonials py-5" id="testi">
		<div class="container py-xl-5 py-lg-3">
			<h3 class="title-w3 mb-5 text-wh font-weight-bold">What Our Customers Say
				<span>Excellent Reviews for our Website</span>
			</h3>
			<div class="carousel-inner">
				<div class="row">
					<div class="col-lg-6 w3_testimonials_grid">
						<div class="bg-wh p-sm-5 p-4">
							<p class="sub-test-w3ls">Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil
								impedit quo minus id quod possimus, omnis voluptas.
							</p>
							<div class="row mt-5">
								<div class="col-3 testi-img-res">
									<img src="{% static 'images/te1.jpg' %}" alt=" " class="img-fluid" />
								</div>
								<div class="col-9 w3_testi_grid mt-xl-3 mt-lg-2 mt-md-4 mt-2">
									<h5 class="mb-2">Thomas Carl</h5>
									<p>Sed do eiusmod</p>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-6 w3_testimonials_grid mt-lg-0 mt-4">
						<div class="bg-wh p-sm-5 p-4">
							<p class="sub-test-w3ls">Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil
								impedit quo minus id quod possimus, omnis voluptas.
							</p>
							<div class="row mt-5">
								<div class="col-3 testi-img-res">
									<img src="{% static 'images/te2.jpg' %}" alt=" " class="img-fluid" />
								</div>
								<div class="col-9 w3_testi_grid  mt-xl-3 mt-lg-2 mt-md-4 mt-2">
									<h5 class="mb-2">Adam Ster</h5>
									<p>Sed do eiusmod</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- //testimonials -->
	{% endblock %}

templates/admintemplates/admincategorylist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}




{% block content %}

 <!-- main-heading -->
            <!-- <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2> -->
'            <!--// main-heading -->

            <!-- Tables content -->
            <section class="tables-section">
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Food List</h4>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">title</th>
                                <th scope="col">Image</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% for foodcategory in allcategory %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{foodcategory.title}}</td>
                                
                                <td>
                                    {% if foodcategory.image %}
                                    <img src="{{foodcategory.image.url}}" width="100">
                                    {% endif %}
                                </td>
                                 <td>
                                    <a href="{% url 'themeapp:admincategoryupdate' foodcategory.id %}" class="btn btn-primary">Update</a>
                                    <a href="{% url 'themeapp:admincategorydelete' foodcategory.id %}" class="btn btn-danger">Delete</a>

                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

               

            </section>'

{% endblock %}

templates/admintemplates/adminfoodcategory.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}




{% block content %}

 <!-- main-heading -->
            <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2>
            <!--// main-heading -->

            <!-- Tables content -->
            <section class="tables-section">
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Category form</h4>
                    <form method="POST" enctype="multipart/form-data">
                    	{% csrf_token %}
                    	{{form.as_p}}
                    	<button>Save</button>
                    </form>
                </div>

               

            </section>

{% endblock %}

templates/admintemplates/adminfoodcategorydelete.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}




{% block content %}

 <!-- main-heading -->
            <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2>
            <!--// main-heading -->

            <!-- Tables content -->
            <section class="tables-section">
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Delete Category</h4>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <button class="btn btn-danger">Delete</button>
                    </form>
                </div>

               

            </section>


{% endblock %}

templates/admintemplates/adminfoodcreate.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}




{% block content %}

 <!-- main-heading -->
            <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2>
            <!--// main-heading -->

            <!-- Tables content -->
            <section class="tables-section">
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Food form</h4>
                    <form method="POST" enctype="multipart/form-data">
                    	{% csrf_token %}
                    	{{form.as_p}}
                    	<button>Save data</button>
                    </form>
                </div>

               

            </section>

{% endblock %}

templates/admintemplates/adminfooddelete.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}




{% block content %}

 <!-- main-heading -->
            <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2>
            <!--// main-heading -->

            <!-- Tables content -->
            <section class="tables-section">
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Delete Food</h4>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <button class="btn btn-danger">Delete</button>
                    </form>
                </div>

               

            </section>


{% endblock %}

templates/admintemplates/adminfoodlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}




{% block content %}

 <!-- main-heading -->
            <!-- <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2> -->
'            <!--// main-heading -->

            <!-- Tables content -->
            <section class="tables-section">
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Food List</h4>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">price</th>
                                <th scope="col">Image</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% for food in foodlist %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{food.name}}</td>
                                <td>Rs.{{food.price}} only</td>
                                <td><img src="{{food.image.url}}" width="100"></td>
                                <td>
                                    <a href="{% url 'themeapp:adminfoodupdate' food.id %}" class="btn btn-primary">Update</a>
                                    <a href="{% url 'themeapp:adminfooddelete' food.id %}" class="btn btn-danger">Delete</a>

                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

               

            </section>'

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
	<title>Organic Food Agriculture Category Bootstrap Responsive Web Template | Home :: W3layouts</title>
	<!-- Meta tag Keywords -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8" />
	<meta name="keywords" content="Organic Food Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!-- //Meta tag Keywords -->

	<!-- Custom-Files -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Bootstrap-Core-CSS -->
	<link href="{% static 'css/css_slider.css' %}" type="text/css" rel="stylesheet" media="all">
	<!-- banner slider -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
	<!-- Style-CSS -->
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
	<!-- Font-Awesome-Icons-CSS -->
	<!-- //Custom-Files -->

	<!-- Web-Fonts -->
	<link href="//fonts.googleapis.com/css?family=Poiret+One&amp;subset=cyrillic,latin-ext" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Mada:200,300,400,500,600,700,900&amp;subset=arabic" rel="stylesheet">
	<!-- //Web-Fonts -->
</head>

<body>
	<!-- main banner -->
	<div class="{% block abc %}{% endblock %}" id="home">
		<!-- header -->
		<header>
			<div class="container-fluid">
				<div class="header d-md-flex justify-content-between align-items-center py-sm-4 py-3 px-xl-5 px-lg-3 px-2">
					<!-- logo -->
					<div id="logo">

						<a class="" href="/"><img src="https://sarobartech.com/media/organizationdetails/sarobar_logo_0DyqH7y.png" height="80"></a>
					</div>
					<!-- //logo -->
					<!-- nav -->
					<div class="nav_w3ls">
						<nav>
							<label for="drop" class="toggle toogle-2">Menu</label>
							<input type="checkbox" id="drop" />
							<ul class="menu">
								<li class="{% block homepage %}{% endblock %}"><a href="/">Home</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2 {% block aboutpage %}{% endblock %}"><a href="{% url 'themeapp:about' %}">About Us</a></li>
								<li class="{% block gallerypage %}{% endblock %}"><a href="{% url 'themeapp:gallery' %}">Gallery</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2">
									<!-- First Tier Drop Down -->
									<label for="drop-2" class="toggle">Dropdown <span class="fa fa-angle-down" aria-hidden="true"></span>
									</label>
									<a href="#">Category <span class="fa fa-angle-down" aria-hidden="true"></span></a>
									<input type="checkbox" id="drop-2" />
									<ul>
										{% for category in mycategorys %}
										<li><a href="#best" class="drop-text">{{category.title}}</a></li>
										{% endfor %}
									</ul>
								</li>
								<li class="{% block contactpage %}{% endblock %}"><a href="{% url 'themeapp:contact' %}">Contact Us</a></li>
							</ul>
						</nav>
					</div>
					<!-- //nav -->
				</div>
			</div>
		</header>
		<!-- //header -->
		{% block banner %}
		{% endblock %}

	</div>
	<!-- //main -->
	{% block body %}
	{% endblock %}







	<!-- footer -->
	<footer class="py-5">
		<div class="container pt-xl-5 pt-lg-3">
			<!-- newsletter -->
			<div class="newsletter_right_w3w3pvt-lau pb-md-5 pb-3" id="newsletter">
				<h2 class="tittle text-wh mb-5 font-weight-bold">Subscribe Newsletter</h2>
				<div class="n-right-w3ls pt-3">
					<form action="#" method="post">
						<div class="row">
							<div class="col-md-4 form-group">
								<input class="form-control" type="text" name="Name" placeholder="Name" required="">
							</div>
							<div class="col-md-4 form-group px-md-0">
								<input class="form-control" type="email" name="Email" placeholder="Email Address" required="">
							</div>
							<div class="col-md-4 form-group mt-md-0 mt-3">
								<button class="form-control btn text-uppercase" type="submit">Subscribe</button>
							</div>
						</div>
					</form>
				</div>
			</div>
			<!-- //newsletter -->
			<!-- footer bottom -->
			<div class="row pt-xl-5 pt-lg-3">
				<!-- button -->
				<div class="col-lg-5 col-md-7 w3l-footer mt-lg-3 text-md-left text-center">
					<ul class="list-unstyled footer-nav-wthree">
						<li class="mr-4">
							<a href="{% url 'themeapp:home' %}" class="active">Home</a>
						</li>
						<li class="mr-4">
							<a class="" href="{% url 'themeapp:about' %}" >About Us</a>
						</li>
						<li class="mr-4">
							<a class="" href="{% url 'themeapp:gallery' %}">Gallery</a>
						</li>
						<li>
							<a class="" href="{% url 'themeapp:contact' %}">Contact Us</a>
						</li>
					</ul>
				</div>
				<!-- //button -->
				<!-- social icons -->
				<div class="col-lg-7 col-md-5 w3social-icons text-md-right text-center mt-md-0 mt-3">
					<ul>
						<li>
							<a href="#" class="rounded-circle">
								<i class="fa fa-facebook-f"></i>
							</a>
						</li>
						<li class="px-2">
							<a href="#" class="rounded-circle">
								<i class="fa fa-google-plus"></i>
							</a>
						</li>
						<li>
							<a href="#" class="rounded-circle">
								<i class="fa fa-twitter"></i>
							</a>
						</li>
					</ul>
				</div>
				<!-- //social icons -->
			</div>
			<!-- //footer bottom -->
			<!-- copyright -->
			<div class="row pt-lg-4 pt-3 text-md-left text-center">
				<p class="col-xl-7 col-lg-8 copy-right-grids mt-lg-1">© 2019 Organic Food. All Rights Reserved | Design by
					<a href="https://w3layouts.com/" target="_blank">W3layouts</a>
				</p>
				<div class="col-xl-5 col-lg-4 text-center mt-lg-0 mt-4">
					<a href="#home" class="move-top"></a>
				</div>
			</div>
			<!-- //copyright -->
		</div>
	</footer>
	<!-- //footer -->

</body>

</html>

templates/login.html
{% extends 'base.html' %}
{% block body %}
	<h3> Login Form</h3>
	<p>{{error}}</p>
<form method="POST">
	{% csrf_token %}

	{{form.as_p}}
	<button>Submit</button>

</form>



{% endblock %}